name: Deploy to GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Lint and format code
        run: npm run lint:fix

      - name: Run Linter
        run: npm run lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Setup Cypress
        uses: cypress-io/github-action@v2

      - name: Run E2E tests
        env:
          CYPRESS_BASE_URL: https://example.com
        run: npm run test:e2e

  build:
    runs-on: ubuntu-latest
    name: Build
    needs:
     - Lint
     - Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build production files
        run: npm run build
